GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "hi",
  "important": true
}

###
GET http://localhost:3001/people

###
GET http://localhost:3001/api/notes/6a0e48a771e2ba848d24d637